# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'music_gen_demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from progress_dialog import Progress_Dialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(667, 447)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #  --- GENERATE BUTTON ---
        self.generateBtn = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.handleGenerateButton())
        self.generateBtn.setGeometry(QtCore.QRect(249, 349, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.generateBtn.setFont(font)
        self.generateBtn.setObjectName("generateBtn")

        #  --- TITLE LABEL ---
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(129, -1, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 80, 511, 182))
        self.widget.setObjectName("widget")

        #  --- GRID LAYOUT  ---
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        #  --- NAME LABEL ---
        self.nameTitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nameTitle.setFont(font)
        self.nameTitle.setObjectName("nameTitle")
        self.gridLayout.addWidget(self.nameTitle, 0, 0, 1, 1)

        #  --- NAME INPUT  ---
        self.nameInput = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nameInput.setFont(font)
        self.nameInput.setObjectName("nameInput")
        self.gridLayout.addWidget(self.nameInput, 0, 1, 1, 1)

        #  --- PROMPT TITLE LABEL ---
        self.promptTitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.promptTitle.setFont(font)
        self.promptTitle.setObjectName("promptTitle")
        self.gridLayout.addWidget(self.promptTitle, 1, 0, 1, 1)

        #  --- PROMPT COMBOBOX ---
        self.promptComboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.promptComboBox.setFont(font)
        self.promptComboBox.setObjectName("promptComboBox")
        self.promptComboBox.addItem("")
        self.promptComboBox.addItem("")
        self.promptComboBox.addItem("")
        self.promptComboBox.addItem("")
        self.promptComboBox.addItem("")
        self.promptComboBox.addItem("")
        self.gridLayout.addWidget(self.promptComboBox, 1, 1, 1, 1)

        #  --- PROMPT LENGTH TITLE LABEL ---
        self.promptLengthTitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.promptLengthTitle.setFont(font)
        self.promptLengthTitle.setObjectName("promptLengthTitle")
        self.gridLayout.addWidget(self.promptLengthTitle, 2, 0, 1, 1)

        #  --- PROMPT LENGTH SLIDER ---
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.promptLengthSlider = QtWidgets.QSlider(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.promptLengthSlider.setFont(font)
        self.promptLengthSlider.setMinimum(50)
        self.promptLengthSlider.setMaximum(100)
        self.promptLengthSlider.setSingleStep(5)
        self.promptLengthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.promptLengthSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.promptLengthSlider.setObjectName("promptLengthSlider")
        self.promptLengthSlider.valueChanged.connect(self.updateSliderLabels)
        self.verticalLayout.addWidget(self.promptLengthSlider)

        #  --- PROMPT LENGTH VALUE LABEL ---
        self.promptValueLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.promptValueLabel.setFont(font)
        self.promptValueLabel.setObjectName("promptValueLabel")
        self.verticalLayout.addWidget(self.promptValueLabel)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)

        #  --- GENERATION LENGTH LABEL ---
        self.genLengthTitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.genLengthTitle.setFont(font)
        self.genLengthTitle.setObjectName("genLengthTitle")
        self.gridLayout.addWidget(self.genLengthTitle, 3, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        #  --- GENERATION LENGTH SLIDER ---
        self.genLengthSlider = QtWidgets.QSlider(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.genLengthSlider.setFont(font)
        self.genLengthSlider.setMinimum(100)
        self.genLengthSlider.setMaximum(1000)
        self.genLengthSlider.setSingleStep(10)
        self.genLengthSlider.setPageStep(20)
        self.genLengthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.genLengthSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.genLengthSlider.setTickInterval(0)
        self.genLengthSlider.setObjectName("genLengthSlider")
        self.genLengthSlider.valueChanged.connect(self.updateSliderLabels)
        self.verticalLayout_2.addWidget(self.genLengthSlider)

        #  --- GENERATION LENGTH VALUE LABEL ---
        self.genValueLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.genValueLabel.setFont(font)
        self.genValueLabel.setObjectName("genValueLabel")
        self.verticalLayout_2.addWidget(self.genValueLabel)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        #  --- MENU BAR ---
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generateBtn.setText(_translate("MainWindow", "Generate"))
        self.title.setText(_translate("MainWindow", "Autocomplete For Music"))
        self.nameTitle.setText(_translate("MainWindow", "Name of Generation"))
        self.promptTitle.setText(_translate("MainWindow", "Pick a prompt"))
        self.promptComboBox.setItemText(0, _translate("MainWindow", "None"))
        self.promptComboBox.setItemText(1, _translate("MainWindow", "Alla Turca"))
        self.promptComboBox.setItemText(2, _translate("MainWindow", "Fur Elise"))
        self.promptComboBox.setItemText(3, _translate("MainWindow", "Clair de Lune"))
        self.promptComboBox.setItemText(4, _translate("MainWindow", "La Campanella"))
        self.promptComboBox.setItemText(5, _translate("MainWindow", "Piano Sonata No. 16"))
        self.promptLengthTitle.setText(_translate("MainWindow", "Prompt Length (Tokens)"))
        self.promptValueLabel.setText(_translate("MainWindow", "Current Prompt Length: 50"))
        self.genLengthTitle.setText(_translate("MainWindow", "Generation Length (Tokens)"))
        self.genValueLabel.setText(_translate("MainWindow", "Current Length: 100"))
    
    # Update the label associated with showing the current value of sliders
    def updateSliderLabels(self):
        promptLength = self.promptLengthSlider.value()
        genLength = self.genLengthSlider.value()

        self.promptValueLabel.setText(f"Current Prompt Length: {promptLength}")
        self.genValueLabel.setText(f"Current Length: {genLength}")

    
    def handleGenerateButton(self):
        print("clicked")
        # Get the text from the nameInput widget
        outputFileName = self.nameInput.text()

        # Get the prompt from the combo box
        selectedPrompt = self.promptComboBox.currentText()

        # Ensure that the output file name is not empty
        if not outputFileName or selectedPrompt == "None":
            QtWidgets.QMessageBox.warning(self.centralwidget,"Warning", "Please enter a valid output file name or valid prompt type.")
            return
        
        # Get the values of the prompt length and generation length sliders
        promptLength = self.promptLengthSlider.value()
        genLength = self.genLengthSlider.value()
            
        print("Output File Name:", outputFileName)
        print("Selected Prompt:", selectedPrompt)
        print("Prompt Length:", promptLength)
        print("Generation Length:", genLength)

        # Open progress dialog window
        self.window = QtWidgets.QDialog()
        self.ui = Progress_Dialog(outputFileName, selectedPrompt, promptLength, genLength)
        self.ui.setupUi(self.window)
        # Store the reference to the dialog in the Progress_Dialog instance
        self.ui.dialog = self.window
        self.window.show()
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
